# Set to true to add assignees to pull requests
addAssignees: true

# A list of reviewers to be added to pull requests (GitHub user name)
# a floating reviewer needs a weight, by default its one
addReviewers: false

reviewers:
    total: 2
    minFixed: 0
    fixed:
        - ankur17
        - AbhijeetKikawat
    floating:
        - tushar8298

# Settings for autoDelete Feature
autoDelete: true

autoDeleteSettings:
    exclude:
        - dev
        - master

# Release drafting
releaseDrafting: true


branchToIssueSettings:
    # will give a warning as comment, if doest not follow the rule
    mandatory: true
    pattern: ^SPRC-[\\d]+
    message: "Please follow the ticket link: [ticket](https://springrole.atlassian.net/browse/<%ticket%>)"
    seperator: true ## --- as default
    position: TOP. # TOP (default)
    errorMsg: Please consider following the ticket pattern for branch naming  # (default) if mandatory=true

slackWebhook: https://hooks.slack.com/services/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
